NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: "intermediatecerts/ica.pem"
    OrganizationalUnitIdentifier: "client"
  AdminOUIdentifier:
    Certificate: "intermediatecerts/ica.pem"
    OrganizationalUnitIdentifier: "admin"
  PeerOUIdentifier:
    Certificate: "intermediatecerts/ica.pem"
    OrganizationalUnitIdentifier: "peer"
  OrdererOUIdentifier:
    Certificate: "intermediatecerts/ica.pem"
    OrganizationalUnitIdentifier: "orderer"
